services:
  - type: web
    name: django-portfolio-site
    env: python
    buildCommand: |
      pip install -r portofolio_kriso/requirements.txt
    startCommand: |
      cd portofolio_kriso && python manage.py collectstatic --noinput && gunicorn portofolio_kriso.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portofolio_kriso.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
